In [49]:
import cv2
import numpy as np

In [50]:
haar_cascade_file = "/home/rogue/Desktop/face_recon_media_segregation/haarcascade_frontalcatface.xml"
haar_cascade = cv2.CascadeClassifier(haar_cascade_file)

In [128]:
imgs_path = ["/home/rogue/Desktop/face_recon_media_segregation/know-faces/sanju_mosi_ji.png" ,
            "/home/rogue/Desktop/face_recon_media_segregation/know-faces/anil_mosa_ji.png"]

imgs = []
for i in imgs_path:
    imgs.append(cv2.imread(i,0))

cv2.imshow("Image",imgs[0])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [129]:
faces = []

for i in imgs:
    # faces.append(haar_cascade.detectMultiScale(i , scaleFactor=1.05 , minNeighbors=0 , minSize=(120,120)))
    faces.append(haar_cascade.detectMultiScale(i , scaleFactor=1.05 , minNeighbors=0 , minSize=(125,125)))

In [130]:
faces = faces[::-1]

In [131]:
faces

[array([[103, 103, 146, 146],
        [103, 109, 146, 146],
        [ 96, 109, 153, 153],
        [ 87, 107, 161, 161],
        [ 84,  99, 169, 169],
        [ 77, 106, 169, 169],
        [ 84, 106, 169, 169],
        [ 92, 106, 169, 169],
        [ 89,  89, 177, 177],
        [ 96,  89, 177, 177],
        [ 74,  96, 177, 177],
        [ 81,  96, 177, 177],
        [ 89,  96, 177, 177],
        [ 96,  96, 177, 177],
        [103,  96, 177, 177],
        [ 74, 103, 177, 177],
        [ 81, 103, 177, 177],
        [ 89, 103, 177, 177],
        [ 96, 103, 177, 177],
        [103, 103, 177, 177],
        [ 93,  78, 186, 186],
        [ 85,  85, 186, 186],
        [ 93,  85, 186, 186],
        [ 78,  93, 186, 186],
        [ 85,  93, 186, 186],
        [ 85, 101, 186, 186],
        [ 93, 101, 186, 186],
        [ 90,  81, 196, 196],
        [ 65,  90, 196, 196],
        [ 73,  90, 196, 196],
        [ 81,  90, 196, 196],
        [ 90,  90, 196, 196],
        [ 73,  98, 196, 196],
        [ 

In [132]:
for i in faces:
    print(i)

[[103 103 146 146]
 [103 109 146 146]
 [ 96 109 153 153]
 [ 87 107 161 161]
 [ 84  99 169 169]
 [ 77 106 169 169]
 [ 84 106 169 169]
 [ 92 106 169 169]
 [ 89  89 177 177]
 [ 96  89 177 177]
 [ 74  96 177 177]
 [ 81  96 177 177]
 [ 89  96 177 177]
 [ 96  96 177 177]
 [103  96 177 177]
 [ 74 103 177 177]
 [ 81 103 177 177]
 [ 89 103 177 177]
 [ 96 103 177 177]
 [103 103 177 177]
 [ 93  78 186 186]
 [ 85  85 186 186]
 [ 93  85 186 186]
 [ 78  93 186 186]
 [ 85  93 186 186]
 [ 85 101 186 186]
 [ 93 101 186 186]
 [ 90  81 196 196]
 [ 65  90 196 196]
 [ 73  90 196 196]
 [ 81  90 196 196]
 [ 90  90 196 196]
 [ 73  98 196 196]
 [ 81  98 196 196]
 [ 90  98 196 196]
 [ 77  77 205 205]
 [ 86  77 202 205]
 [ 68  86 205 205]
 [ 77  86 205 205]
 [ 86  86 202 205]
 [ 68  94 205 205]
 [ 77  94 205 205]
 [ 86  94 202 205]
 [ 72  72 216 216]
 [ 63  81 216 216]
 [ 72  81 216 216]
 [ 54  90 216 216]
 [ 63  90 216 216]
 [ 72  90 216 216]
 [ 66  75 222 226]
 [ 50  69 238 238]]
[[ 26  32 126 126]
 [ 32  32 1

In [133]:
faces_img=[]

print(len(faces),len(imgs))

# for i in range(len(faces)):
#     # i = list(i)
#     # for j in len(i):

i=1

print(len(faces[i]))

for x,y,w,h in faces[i]:
    print("yo")
    print((x,y,w,h))
    temp = imgs[1][y : y+h , x : x+w]
    # cv2.imshow("temp",imgs[0])
    # cv2.waitKey(0)
    # cv2.destroyAllWindows()
    faces_img.append(temp)

print((faces_img[0]))
cv2.imwrite("Image0.jpg" , faces_img[0])
cv2.imwrite("Image1.jpg" , faces_img[1])
# cv2.imwrite("Image2.jpg" , faces_img[2])
# cv2.imwrite("Image3.jpg" , faces_img[3])

2 2
2
yo
(np.int32(26), np.int32(32), np.int32(126), np.int32(126))
yo
(np.int32(32), np.int32(32), np.int32(126), np.int32(126))
[[155 149 146 ...  88 110 105]
 [155 156 148 ... 127 103  96]
 [154 152 149 ... 133  97  90]
 ...
 [139 136 131 ... 105 107 105]
 [136 138 130 ...  84  97 102]
 [134 121 122 ...  90  91  85]]


True